apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-1g
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/k8s-pvs/manual-pv-1
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-2g
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /var/lib/k8s-pvs/manual-pv-2
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem

---