apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: puc-devops-role-binding        # <- Nome do RoleBinding. Pode ser qualquer coisa, recomenda-se algo descritivo
subjects:
- kind: User
  name: puc-devops                     # <- Nome do usuário que terá acesso, será extraído do CN certificado que criamos
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-reader                     # <- Nome da Role que será aplicada
  apiGroup: rbac.authorization.k8s.io