apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-user-puc-devops        # <- Nome do RoleBinding. Pode ser qualquer coisa, recomenda-se algo descritivo
  namespace: kube-system               # <- Namespace onde o RoleBinding será aplicado
subjects:
- kind: User
  name: puc-devops                     # <- Nome do usuário que terá acesso, será extraído do CN certificado que criamos
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader                     # <- Nome da Role que será aplicada
  apiGroup: rbac.authorization.k8s.io